/**
 * Created by Chris Home Desktop on 6/20/2018.
 */

@IsTest
private class CongrComm_ChildrenFormCtrlTests {
//
//    @TestSetup public static void SetupTest(){
//        /// creates static comm user
//        TestObjectFactory.CreateCommunityTestUser(false);
//        list<Contact> contacts = (list<Contact>)TestObjectFactory.CreateContacts('test',1);
//    }
//
//    static testMethod void testBehavior() {
//
//        Contact theCon = [SELECT Id FROM Contact limit 1];
//        /// retrieves user created above.
//        User theUser = [SELECT Id FROM User ORDER BY CreatedDate DESC limit 1] ;
//        system.runAs(theUser) {
//
//            PageReference pageRef = Page.CongrComm_ChildrenForm;
//            pageRef.getParameters().put('id', String.valueOf(theCon.Id));
//            Test.setCurrentPage(pageRef);
//
//            CongrComm_ChildrenFormCtrl childFormCtrl = new CongrComm_ChildrenFormCtrl();
//            childFormCtrl.getURLParams();
//            childFormCtrl.Save();
//        }
//
//
//    }
}